### ISSUE TITLE
Not found ./tools/immutabler/core.rb

### ISSUE THREAD

**Issue by rowwingman** [techery/flux-todo-app#1]
`Run Script` script inside `ModelGenerator` executes with errors:
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ./tools/immutabler/core.rb (LoadError)
    from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /Users/marko1503/Downloads/flux-todo-app-master/Pods/FLUX/Pod/Classes/flux_models.rb:1:in `<main>'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require': cannot load such file -- immutabler (LoadError)
    from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/marko1503/Downloads/flux-todo-app-master/ToDoApp/Stores/ToDoModels.rb:1:in`<main>'
Command /bin/sh failed with exit code 1

**Comment by goncharik** [comment]
Please try to instal `immutabler` gem first:

```
[sudo] gem install immutable
```

**Comment by rowwingman** [comment]
I've already tried it. The issue doesn't fix.

sudo gem install immutabler
Password:
Fetching: handlebars-source-3.0.3.gem (100%)
Successfully installed handlebars-source-3.0.3
Fetching: libv8-3.16.14.13-x86_64-darwin-14.gem (100%)
Successfully installed libv8-3.16.14.13-x86_64-darwin-14
Fetching: ref-2.0.0.gem (100%)
Successfully installed ref-2.0.0
Fetching: therubyracer-0.12.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed therubyracer-0.12.2
Fetching: handlebars-0.7.0.gem (100%)
Successfully installed handlebars-0.7.0
Fetching: immutabler-0.1.6.gem (100%)
Successfully installed immutabler-0.1.6
Parsing documentation for handlebars-source-3.0.3
Installing ri documentation for handlebars-source-3.0.3
Parsing documentation for libv8-3.16.14.13-x86_64-darwin-14
Installing ri documentation for libv8-3.16.14.13-x86_64-darwin-14
Parsing documentation for ref-2.0.0
Installing ri documentation for ref-2.0.0
Parsing documentation for therubyracer-0.12.2
Installing ri documentation for therubyracer-0.12.2
Parsing documentation for handlebars-0.7.0
Installing ri documentation for handlebars-0.7.0
Parsing documentation for immutabler-0.1.6
Installing ri documentation for immutabler-0.1.6
Done installing documentation for handlebars-source, libv8, ref, therubyracer, handlebars, immutabler after 1 seconds
6 gems installed

**Comment by goncharik** [comment]
Could you execute ruby file directly from the command line in terminal:

```
ruby /Users/marko1503/Downloads/flux-todo-app-master/ToDoApp/Stores/ToDoModels.rb
```

**Comment by rowwingman** [comment]
Yes, and it finishes with success. Models are generated. But in xCode I still have an error in ModelGenerator
